- colcon_cmake/task/cmake/test.py
While I couldn't find any documentation about it `CTest` returns `8` when tests are failing. Since tests failures should not be considered an "error" in terms of invoking the `test` verb that case is handled differently. This unifies the return value semantic across other types.
Before the failing bridge test made the build fail: https://ci.ros2.org/view/colcon/job/colcon_ci_packaging_linux-aarch64/5/
After the failing bridge test make the build only unstable: https://ci.ros2.org/view/colcon/job/colcon_ci_packaging_linux-aarch64/7/
> use rc 0 when CTest has failing tests

- appveyor.yml
- colcon_cmake/task/cmake/build.py
Add new options:
* to build a specific target (`--cmake-build-target`) instead of the default ones and
* to `clean` before building (`--cmake-clean-first`).
> add --cmake-target and --cmake-clean-first options

- colcon_cmake/task/cmake/build.py
- colcon_cmake/task/cmake/test.py
The help text for `--cmake-args` now says to quote a space if using cmd on windows.
```
Arguments for 'cmake' packages:
--cmake-args [* [* ...]]
Arbitrary arguments which are passed to all CMake
projects. Args that start with "-" must be prefixed
with a space. If using bash then use
--cmake-args \ -Dvar=val
If using Windows cmd then use
--cmake-args " -Dvar=val"
```
```
Arguments for 'cmake' packages:
--ctest-args [* [* ...]]
Arbitrary arguments which are passed to all CTest
projects. Args that start with "-" must be prefixed
with a space. If using bash then use
--ctest-args \ -L label
If using Windows cmd then use
--ctest-args " -L" label
```
connects to colcon/colcon-cmake#6
> Document --cmake-args needs a quoted space before an argument with a dash on windows

- colcon_cmake/task/cmake/build.py
If a package doesn't set the project name in CMake it can't be built with `cmake --build`.
E.g. [geometry2](https://github.com/ros/geometry2/blob/9aa34bf83a9dbcd5bff4c8e1dda2690ae9900eff/test_tf2/CMakeLists.txt#L3-L7).
> check for project name

- colcon_cmake/environment/cmake_module_path.py
Currently the environment hooks are being generated in (depending in where the CMake module was found):
```
<prefix>/share/<pkgname>/cmake/Modules/share/<pkgname>/hook/cmake_module_path.bat
```
and the appended path points to:
```
<prefix>
```
With this patch the location of the environment hook is not nested anymore:
```
<prefix>/share/<pkgname>/hook/cmake_module_path.bat
```
and the appended path is the directory containing the CMake module:
```
<prefix>/share/<pkgname>/cmake/Modules
```
The first fix is just cosmetic. The second one avoid cross-talk between packages (one extending the module path and another one benefiting from it).
Additionally the patch fixes the case where a package installs multiple CMake module into different location. Before the last hook was overwriting all …
> fix CMAKE_MODULE_PATH env var

- colcon_cmake/environment/cmake_module_path.py
- test/spell_check.words
Follow up of #19. See the problem description in [this comment](https://github.com/colcon/colcon-cmake/pull/19#issuecomment-398828746).
This should cut the number of sourced scripts by half (in the case of non-isolated installs with a ROS 2 workspace).
> fix duplicate CMAKE_MODULE_PATH hooks in case of a merged install

- colcon_cmake/task/cmake/build.py
- test/spell_check.words
Since some CI providers like Circle CI limit the CPUs allocated to the container it is beneficial to use that information for the upper limit of jobs.
Similar to colcon/colcon-parallel-executor#17.
> consider sched_getaffinity when limiting parallel jobs

- colcon_cmake/task/cmake/test.py
To provide a better error message to the user.
E.g. in this case: https://ci.ros2.org/view/nightly/job/nightly_linux-centos_repeated/4/console#console-section-30
> add assert message if build_base doesn't exist

- colcon_cmake/task/cmake/build.py
When trying to build a cmake package with cmake 3.14 and Visual Studio 2019, I see the following error:
~~~
Traceback (most recent call last):
File "c:\users\scpet\desktop\ws\py_colcon_venv\lib\site-packages\colcon_core\executor\__init__.py", line 91, in __call__
rc = await self.task(*args, **kwargs)
File "c:\users\scpet\desktop\ws\py_colcon_venv\lib\site-packages\colcon_core\task\__init__.py", line 92, in __call__
return await task_method(*args, **kwargs)
File "c:\users\scpet\desktop\ws\py_colcon_venv\lib\site-packages\colcon_cmake\task\cmake\build.py", line 85, in build
rc = await self._reconfigure(args, env)
File "c:\users\scpet\desktop\ws\py_colcon_venv\lib\site-packages\colcon_cmake\task\cmake\build.py", line 160, in _reconfigure
.format_map(locals()))
RuntimeError: Unknown / …
> cmake/build.py: support Visual Studio 16 2019

- colcon_cmake/test_result/ctest.py
- setup.cfg
- stdeb.cfg
- test/spell_check.words
Closes #40. Requires colcon/colcon-test-result#20.
Before merging a version dependency on the upcoming `colcon-test-result` package needs to be added.
> add test result extension for CTest result files

- colcon_cmake/task/cmake/build.py
Closes #45.
For VS 15 and older the default architecture is `Win32`. Instead of hard coding `Win64` as part of the generator name this patch passes the `-A` option and also allows the user to pass a custom value.
> support CMake -A option to select architecture on Windows

- colcon_cmake/task/cmake/build.py
Before the make flags are only used for the `build` target. This change also applies them to the `install` target.
> add -j / -l to install target

- colcon_cmake/task/cmake/build.py
Beginning from [`Visual Studio 2017 15.4`](https://devblogs.microsoft.com/cppblog/cmake-support-in-visual-studio/), the toolchain comes with `CMake` and `Ninja` built-in support. It would be great to see Windows developers can have the free choice on what generator to use. This pull request is to unblock the hard-coded decision in `colcon-cmake` and allow developers to pass `--cmake-args -G Ninja` to specify the generator by their choices.
> Provide options for generator override on Windows.

- colcon_cmake/task/cmake/build.py
Removed special case code for Visual Studio generator using MSBUILD. "cmake --build" with "--target install" has the same effect and removed the need for special case code.
> cmake_install always invokes --build --target install

- colcon_cmake/__init__.py
- colcon_cmake/task/cmake/__init__.py
- colcon_cmake/task/cmake/build.py
- test/spell_check.words
- test/test_parse_cmake_version.py
Make use of CMake '--install' option introduced in 3.15. Only performs installation, whereas '--build <dir> --target install' would first (re)build. Using '--install' is a significantly faster installation process when using Visual Studio as various overheads are avoided.
> Use 'cmake --install' where available

- colcon_cmake/test_result/ctest.py
- test/spell_check.words
before
```
colcon test-result --verbose                        
build/osrf_testing_tools_cpp/Testing/20200212-2242/Test.xml: 4 tests, 0 errors, 1 failure, 0 skipped
Summary: 4 tests, 0 errors, 1 failure, 0 skipped
```
After:
```
colcon test-result --verbose
build/osrf_testing_tools_cpp/Testing/20200212-2242/Test.xml: 4 tests, 0 errors, 1 failure, 0 skipped
- (test_osrf_testing_tools_cpp_filter_versions_cmake)
<<< failure message
CMake Error: Error processing file: /opt/ros/master/src/osrf/osrf_testing_tools_cpp/osrf_testing_tools_cpp/test/cmake/test/cmake/test_osrf_testing_tools_cpp_filter_versions.cmake
>>>
Summary: 4 tests, 0 errors, 1 failure, 0 skipped
```
> Add details to CTest test results

- stdeb.cfg
After installing `colcon-core` from apt, I am unable to build a CMake package despite having `colcon-cmake` installed. For convenience it would be good to have an explicit dependency on `cmake` for the debs of colcon-cmake
> add dependency on cmake in Debian package

- colcon_cmake/task/cmake/build.py
- colcon_cmake/task/cmake/test.py
Follow up of colcon/colcon-core#334.
The minimum version dependency on `colcon-core` has already been bumped in #69.
> avoid deprecated colcon_core.task.check_output

- colcon_cmake/test_result/ctest.py
- test/spell_check.words
As per docs:
https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getchildren
```
getchildren()
Deprecated since version 3.2, will be removed in version 3.9: Use list(elem) or iteration.
```
> Fix crash under Python3.9

- .travis.yml
- setup.cfg
The files in the `test` directory are getting installed as an additional package.
The `__init__.py` was added in #57, so this bug has existed since 0.2.18.
> Exclude test directory from package search

- colcon_cmake/task/cmake/build.py
Fixes the following case:
* `cmake` (configuration, no build / test) returns a non-zero error code
* but completes the generation step
E.g. see http://build.ros2.org/view/Fci/job/Fci__nightly-cyclonedds_ubuntu_focal_amd64/89/console#console-section-50
<details>
<summary>CMake output</summary>
```
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/lib/ccache/cc
-- Check for working C compiler: /usr/lib/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX …
```
> ensure to reconfigure after failed invocations

- colcon_cmake/task/cmake/__init__.py
CMake supports generators specified using '-G <generator>' (2 arguments) or as '-G<generator>' (1 argument). This change adds colcon support for the latter, one argument syntax.
> Handle cmake '-G<generator>' syntax

- colcon_cmake/task/cmake/test.py
- test/spell_check.words
> Copy CTest results to custom location

- colcon_cmake/task/cmake/build.py
Instead of grabbing the colcon process environment variables to determine what MAKEFLAGS will be when the process is invoked, grab the actual environment variables under which MAKE will be invoked.
> Use command environment for determining MAKE args

- colcon_cmake/task/cmake/build.py
- colcon_cmake/test_result/ctest.py
- setup.cfg
Introduced by python/importlib_metadata # 298.
Move `noqa` comments to pass latest version of `flake8`.
Closes #108.
> suppress deprecation warning in flake8

- colcon_cmake/task/cmake/__init__.py
The `Ninja Multi-Config` generator was introduced as part of CMake 3.17 supporting debug and release artefacts under the same `build` directory, like `Xcode` or `Visual Studio`. This change allows colcon to recognise `Ninja Multi-Config` as a mult-config generator and as a Ninja generator.
Note that in practice this change does not support an `apt-get` install of CMake on versions of current Ubuntu LTS releases - Unbutu 20.04 (latest current LTS) provided CMake version 3.16.
Change summary:
- Add `Ninja Multi-Config` to the set of generators where `is_multi_configuration_generator()` is `True`
> Add support for `Ninja Multi-Config`

- colcon_cmake/task/cmake/__init__.py
While building, I received this error at the line corrected:
```TypeError: argument of type 'NoneType' is not iterable```
This happens because get_variable_from_cmake_cache() returns None. This line fixes it.
> Fix TypeError when CMAKE_GENERATOR isn't present

- colcon_cmake/task/cmake/__init__.py
- colcon_cmake/task/cmake/build.py
- setup.cfg
- stdeb.cfg
This is an API breaking change, but I don't really see a good way to avoid it.
@KazNX FYI
> Use packaging.version in place of pkg_resources.parse_version

- colcon_cmake/package_identification/cmake.py
While I don't think we should discriminate between dependency origins for general use, this is useful metadata in some contexts and is easy to include.
Follows colcon/colcon-core#564
> Add 'origin' metadata to cmake dependencies

- colcon_cmake/task/cmake/__init__.py
This specifies a buildfile for the Visual Studio generator, so cmake will not always reconfigure.
Fixes #111
> Specify buildfile for Visual Studio generator

- test/spell_check.words
- test/test_task_cmake_build.py
This change introduces a basic test of the CMake build task. It requires that 'cmake' is installed, and is skipped when the 'cmake' executable can't be found.
> Port build task test from colcon_core to colcon_cmake

- colcon_cmake/task/cmake/__init__.py
In what I can only call an absolute blunder, `colcon-cmake` 0.2.28 included both a change to fix this exception (#128) and a subsequent change which added the same bug (#114). I failed to connect the dots :facepalm:
Thanks to @FelixPe for [pointing this out](https://github.com/colcon/colcon-cmake/pull/114#issuecomment-2309823537).
> Fix (another) TypeError when CMAKE_GENERATOR isn't present
