colcon/colcon-cmake

colcon_cmake/package_identification/cmake.py

this allows for reuse in this package and for extension wanting to leverage that feature (e.g. https://github.com/eProsima/Fast-RTPS/pull/207#issuecomment-383248609)

expose API to extract find_package-like CMake function calls

---

colcon_cmake/task/cmake/test.py

Connect to colcon/colcon-core#41.

post TestFailure event in case CTest reports failed tests

---

README.rst
setup.cfg

Connect to colcon/colcon-core#51.

update package metadata

---

colcon_cmake/task/cmake/build.py

Fixes colcon/colcon-core#57.
Custom parameters can still be passed by setting the environment variable `CL` (similar to `MAKEFLAGS` for Make).

use multiple processes by default with Visual Studio

---

colcon_cmake/task/cmake/build.py
colcon_cmake/task/cmake/test.py

Same as ament/ament_tools#187.

allow MinSizeRel and RelWithDebInfo on Windows

---

colcon_cmake/task/cmake/build.py
colcon_cmake/task/cmake/test.py

Follow up of colcon/colcon-core#63.

update help text for greedy options

---

colcon_cmake/task/cmake/build.py

The CMake invocation `cmake --build . --cmake-target foo` fails when `foo` is not a valid target in the project. When building a whole ROS 1 workspace we want to build only the tests using the target `tests`. Since some packages might not have any tests the target isn't always available. Hence we need this new option to just skip packages which don't have the requested target.

add option --cmake-target-skip-unavailable

---

colcon_cmake/package_identification/cmake.py
colcon_cmake/task/cmake/build.py
setup.cfg

Similar to colcon/colcon-core#109.

update log.warn (deprecated) to log.warning

---

colcon_cmake/package_identification/cmake.py

match case insensitive function names

---

colcon_cmake/task/cmake/build.py
test/test_flake8.py

Same as colcon/colcon-core#127.

Fix flake8 test logic

---

colcon_cmake/task/cmake/build.py

New argument required for colcon/colcon-ros#44.

add callback argument to manipulate environment

---

colcon_cmake/task/cmake/build.py

Enabling colcon/colcon-ros#48.

allow additional targets for CMake build

---

colcon_cmake/task/cmake/build.py

fix check of return code

---

colcon_cmake/task/cmake/build.py

Follow up of #32.
@paulbovbel FYI

fix return type

---

colcon_cmake/task/cmake/build.py

Fixes exception reported in colcon/colcon-core#189.

fix variable name in warning

---

colcon_cmake/task/cmake/build.py

Fixes regression from https://github.com/colcon/colcon-cmake/pull/46#discussion_r292695980

fix new condition when args.cmake_args is None

---

colcon_cmake/test_result/ctest.py

Support for colcon/colcon-test-result#29

support the option to delete test result files

---

colcon_cmake/test_result/ctest.py

Detected using this new feature: colcon/colcon-core#232.

use non-deprecated logger API

---

colcon_cmake/task/cmake/build.py
colcon_cmake/task/cmake/test.py

Similar to colcon/colcon-core#328. Partially addresses colcon/colcon-cmake#70.

add note to help message that stdout might not be shown by default

---

colcon_cmake/task/cmake/build.py
colcon_cmake/task/cmake/test.py

Similar to colcon/colcon-core#235.

rename rc -> completed

---

colcon_cmake/task/cmake/build.py
test/spell_check.words

Just for shorter, more readable code.

use contextlib.suppress

---

colcon_cmake/event_handler/compile_commands.py

Fixes #81.
It not only skips the (re-)generation of the workspace-level `compile_commands.json` file when `colcon test` is invoked as described in the referenced ticket but also skips it when e.g. only non-CMake packages are being built.

only generate workspace-level compile_commands.json when CMake was invoked

---

setup.cfg

Precisely what the title says.

add Michel as package maintainer

---

colcon_cmake/event_handler/compile_commands.py

Refer to the docs:
https://docs.python.org/3/library/os.path.html#os.path.getmtime
https://github.com/osrf/buildfarmer/issues/145

👩‍🌾 Fix flake8: specify exception

---

colcon_cmake/task/cmake/build.py

This PR adds support for Visual Studio 2022 (Visual Studio Version 17)

Add support for Visual Studio 2022

---

test/spell_check.words
test/test_package_identification_cmake.py

No change in behavior - just adding tests

Port package_identification tests from colcon_core
